### ISSUE TITLE
Override the default initial version number for the generated package

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#104]
Currently, when you generate a new package with PkgTemplates, the generated package always has `version = "0.1.0"`.

It would be great if I could customize the initial version number.

Ideally, there would be a `initial_version::VersionNumber` keyword argument to `Template`.

**Comment by christopher-dG** [comment]
In the above PR, I added a `version` keyword to the `ProjectFile` plugin.

```jl
Template(; plugins=[ProjectFile(; version=v"1")])
```
