### ISSUE TITLE
Interactive code: Template(; interactive=true)

### ISSUE THREAD

**Issue by christopher-dG** [invenia/PkgTemplates.jl#110]
This is basically a reminder for myself as it's blocking the 0.7 release.

Basically my priority is to not have to write N interactive constructors for N plugins, I should be able to implement something for `Plugin` that goes over the field names (kind of like `show` does). 

I was thinking of putting it into a separate package but I think I'll not do that for now.

**Comment by nickrobinson251** [comment]
Do you have a timeline for this @christopher-dG? Sure would be nice to see all your great work on 0.7 get out the door!

**Comment by christopher-dG** [comment]
Sorry, this will definitely happen eventually -- I've just been busy and working on some other stuff in my free time. I'd say maybe mid-February. Realistically it's a day or two's good work, but the final polish always takes a while.

**Comment by christopher-dG** [comment]
FYI I have this penciled in for this weekend, feel free to bug me if I haven't committed anything by mid-Saturday your time, Nick :sweat_smile:.

**Comment by nickrobinson251** [comment]
👋

**Comment by christopher-dG** [comment]
heh, it's happening. nothing pretty to push yet though :man_shrugging:

**Comment by christopher-dG** [comment]
I'm looking into doing something really fancy with TextUserInterfaces.jl now... it might be a rabbit hole but it could also turn out pretty cool.

**Comment by nickrobinson251** [comment]
😺

**Comment by christopher-dG** [comment]
:hamster:  

(please do keep bugging me until I do this)
