### ISSUE TITLE
Default documentation

### ISSUE THREAD

**Issue by bramtayl** [invenia/PkgTemplates.jl#12]
If looks like the default documentation is just badges at the moment. What about a default with index and autodocs? Something like this?

```
# SessionHacker.jl

## Index

\```@index
\```

\```@autodocs
Modules = [SessionHacker]
\```
```

(ignore the backslashes, I'm having formatting issues)

**Comment by christopher-dG** [comment]
I didn't really know about `@autodocs` until now. Good idea!
