### ISSUE TITLE
Simplify package creation

### ISSUE THREAD

**Issue by ssfrr** [invenia/PkgTemplates.jl#128]
I don't create new packages very often, so when I do I always end up needing to look at the PkgTemplates docs, realize that I need to create a `Template` first, and then call that template, but then I realize that makes a default package with no plugins, so then I look again to figure out how to do it interactively, or what the options are.

For my use-case it's not really important that the process be repeatable, because in the time between creating packages the landscape has often changed anyways.

What do you think about having:

```julia
generate() = generate(prompt_for_pkgname())

function generate(pkgname)
    t = interactive_template()
    t(pkgname)
end
```

So then as a user I can just do:

```julia
using PkgTemplates
PkgTemplates.generate()
```

which is easy to remember and easy to use.

**Comment by christopher-dG** [comment]
The planned new interactive API is `Template(; interactive=true)("PkgName")`, how does that sound?
There could be a no-arg method that prompts for a package name too.

**Comment by ssfrr** [comment]
still seems more complicated than `generate()` -  it requires a keyword argument and the idea that you're creating a callable type, which isn't super standard. Also tab completion isn't useful for keyword arguments so it would probably still require some documentation lookup.

I think in general for me the separation between creating a template and then using it isn't something that I actually would use - I'm generally only creating one package so the two-step process just adds complexity.

Given the new interactive API, what do you think about adding `generate` as a convenience wrapper for one-step package creation? One nice thing is the user can just do `PkgTemplates.<TAB>` and `generate` will be a tempting target.

Another option would be to take a page from BinaryBuilder.jl and have `PkgTemplates.run_wizard()`.

**Comment by christopher-dG** [comment]
The separated template and package-generation is definitely not going away, because some people do make use of saving and reusing templates (e.g. the company that paid me to write this package :sweat_smile:)

But yes a `generate` "alias" certainly seems fine to me!

**Comment by ssfrr** [comment]
Oh yeah, I definitely didn't mean to imply the two-step process is not useful in general, just not for my use-case. I'll probably hold off until things stabilize and then I can submit a PR for `generate` if no one gets there first.

**Comment by rapus95** [comment]
I guess what is really missing is not a convenient short Code-style syntax since that is designed to be repeatedly used and placed in a file but integration into the pkg REPL mode (or another mode) which is designed for interactive use which is definitively the case here. So in fact mirroring the Pkg API landscape with a repl mode API which calls the interactive variants and a function API which can be called in packages. Maybe even aswell a macro variant API.

**Comment by CarloLucibello** [comment]
I really wish the OP solution to be implemented now, until something better comes around. For the latest PkgTemplates version, it should be modified to

```julia
generate() = generate(prompt_for_pkgname())

function generate(pkgname)
           t = interactive_template()
           PkgTemplates.generate(pkgname, t)
end
```
