### ISSUE TITLE
Update workflows for githubactions + documenter + tagbot

### ISSUE THREAD

**Issue by ericphanson** [invenia/PkgTemplates.jl#130]
One needs a few extra steps to have GithubActions CI build docs hosted on GitHub, and to also have TagBot trigger stable docs builds:

* For the first, one needs to add an ssh key for documenter docs to deploy from github actions (i.e. https://github.com/JuliaDocs/Documenter.jl/issues/1177). Example: https://github.com/ericphanson/UnbalancedOptimalTransport.jl/blob/8585054cccb74a05a4624f1f915b9600f036eab2/.github/workflows/ci.yml#L50
* For the second, one needs to add an ssh key to tagbot so it can trigger the stable docs build (https://github.com/JuliaRegistries/TagBot/pull/49). Example: https://github.com/ericphanson/UnbalancedOptimalTransport.jl/blob/8585054cccb74a05a4624f1f915b9600f036eab2/.github/workflows/TagBot.yml#L12
* For some reason, once the latter is added, one then runs into an unknown host issue for the docs build, so needs to add a keyscan step (https://github.com/JuliaRegistries/TagBot/pull/49#issuecomment-575850173). The strange bit is that this issue didn't arise without tagbot in the picture. Example: https://github.com/ericphanson/UnbalancedOptimalTransport.jl/blob/8585054cccb74a05a4624f1f915b9600f036eab2/.github/workflows/ci.yml#L40-L42

It would be great if PkgTemplates could incorporate these modifications so that github actions + documenter + tagbot all works together without needing extra steps. (Of course, the user will still have to add the key as a secret by hand, like in the case for travis).

**Comment by christopher-dG** [comment]
Thanks for reporting, I'll add the new plugin options to the plugin soon. 

For the third one, I still think this should go into Documenter but I can look into adding it as a separate step here too.  I've noticed that it doesn't happen if you run a shell script rather than a Docker container, so presumably the shell environment has its hosts sorted out for GitHub already.

**Comment by ericphanson** [comment]
Thanks! (And thanks for all your help over on the tagbot issue). I'll ask on the Documenter issue https://github.com/JuliaDocs/Documenter.jl/issues/625 about whether it should be handled in Documenter proper, or in the github actions CI file.
