### ISSUE TITLE
Stable version output does not produce docs on travis

### ISSUE THREAD

**Issue by kmsquire** [invenia/PkgTemplates.jl#132]
On the released version of `PkgTemplates.jl` (v0.6.3), the `.travis.yml` file contains both a `matrix` section and a `jobs` section.  

These are aliases, and because both exist, one overwrites the other (in this case, `matrix` overwrites `jobs`.

Example: https://travis-ci.com/kmsquire/ArgParse2.jl/jobs/281357698/config 
(The error is in the middle of the page.)

Because of this configuration issue, documentation generation is not run.  It can be fixed by merging the `matrix` and `jobs` sections.

This has already been done on `master`, but since that is not ready to be released yet, I'm wondering if there is interest in updating the latest tagged version and releasing v0.6.4, so that people using the released version don't run into this issue?

(I don't mind working on this--it should be a simple fix--although I don't think there's currently a target branch available for a pull request targeting v0.6.3/stable.)

If master is about to be released or there's no interest in releasing a v0.6.4, please close this.

**Comment by christopher-dG** [comment]
Thanks for the report. I've created a new branch: `release-0.6.3`. Feel free to PR against that!
