### ISSUE TITLE
Hook into pkg REPL mode

### ISSUE THREAD

**Issue by rapus95** [invenia/PkgTemplates.jl#135]
Once Pkg.generate is removed it would be very nice if PkgTemplates could hook into the repl mode to allow for a convenient syntax in the simple or default cases.
See also: https://github.com/invenia/PkgTemplates.jl/issues/128#issuecomment-584566108

**Comment by christopher-dG** [comment]
See this issue instead: https://github.com/JuliaLang/Pkg.jl/issues/1762
