### ISSUE TITLE
ERROR: LoadError: UndefVarError: License not defined

### ISSUE THREAD

**Issue by Student2Pro** [invenia/PkgTemplates.jl#137]
new to this, just follow user guide
![批注 2020-02-12 184911](https://user-images.githubusercontent.com/59324381/74328181-6f0ad400-4dc8-11ea-8d83-9f01d3430a86.png)
I run it and this happen
![批注 2020-02-12 184912](https://user-images.githubusercontent.com/59324381/74328425-d1fc6b00-4dc8-11ea-9d92-91c02b9034a8.png)
what should I do to fix it?
I'm using juliapro 1.2.0-2

**Comment by christopher-dG** [comment]
You're on PkgTemplates v0.6.3 presumably, your code is for the master branch. Update PkgTemplates with `pkg> add PkgTemplates#master` and you should be fine.

**Comment by Student2Pro** [comment]
> 
> 
> You're on PkgTemplates v0.6.3 presumably, your code is for the master branch. Update PkgTemplates with `pkg> add PkgTemplates#master` and you should be fine.

it worked, thx a lot
