### ISSUE TITLE
Merge with PkgDev into a new package in the long run?

### ISSUE THREAD

**Issue by rapus95** [invenia/PkgTemplates.jl#144]
@christopher-dG @davidanthoff
Now, that PkgTemplates is doing a full rewrite and will open the possibilities to include capabilities which currently are in PkgDev, while PkgDev had a partial rewrite aswell, would it make sense to merge the features of PkgDev and PkgTemplates and choose a new package name which clearly unifies both capabilities?

Reason: I'd like to add the capabilities needed for managing private packages but don't know into which code I should dig since both packages would have a use case for it. Sure, I could create a new package which then could be used by both of them, but it'd be nicer if there was a clear choice. That is, decreasing effort to contribute to the development cycle universe is a good thing.

maybe something entirely new as
- ReleaseCycle
- PkgPublisher (eventually w/o Pkg part)
- PkgManager
- PkgDeployer
- PkgButler (this entirely depends upon what @davidanthoff thinks about it)

Please don't shut the idea down immediatly, I know, the hardest problem will be to find an API which everyone likes. But in the long run having only a single API is worth it IMO.

See also: https://github.com/JuliaLang/PkgDev.jl/issues/168

**Comment by christopher-dG** [comment]
I don't think I really see the benefit here. I can kind of see the appeal of "one package that does everything related to development" but that's a gigantic scope, kind of akin to unifying all the packages that provide array types into Arrays.jl.

As it stands, PkgTemplates and PkgDev have literally nothing in common except that they're both for package developers, and there are a lot of packages with that audience.

To address your more specific goals, PkgTemplates doesn't care at all where your Git repo ends up so it doesn't really need any special handling around that stuff. Invenia uses PkgTemplates to make loads of repos both private and public. So I can say for sure that if you're looking at private package management, PkgDev, RegistryTools, Registrator, etc. are where you should be looking.

**Comment by davidanthoff** [comment]
I think the philosophies here are bit different: if I understand PkgTemplates.jl properly, it is meant as a one-time thing that you use at package creation time, right?

PkgDev (and PkgButlerEngine in particular) takes a different approach: it is really meant as a continuous monitoring of a repo that constantly makes sure that the "boring" stuff in the repo is right and up-to-date.

There is of course a kind of overlap: PkgButlerEngine has the idea of a `template`, and the choice of that essentially dictates what parts of your repo will be monitored by the butler. I'd love to see more templates in PkgButlerEngine, but they can't be one-time-at-pkg-creation things, it needs to be code that takes an existing repo and updates it to conform with whatever rules/stuff comes with that template. Not sure how that fits into the philosophy of this package here.

**Comment by christopher-dG** [comment]
Yeah that's correct, right now PkgTemplates is for nothing but creating brand new packages. Eventually it will probably support updates as well since that's a feature that some people want.

The bigger difference between this and PkgButler seems to be that PkgButler isn't really going for customization, whereas that's PkgTemplates' whole shtick.

**Comment by rapus95** [comment]
> As it stands, PkgTemplates and PkgDev have literally nothing in common except that they're both for package developers, and there are a lot of packages with that audience.

As you already noted yourself that might be true right now but is subject to change. There's the overlap of updating existing packages to match a given template (see also: https://github.com/invenia/PkgTemplates.jl/issues/16).
And as that's an often wanted feature, tell me, where should that capability go to? PkgTemplates or PkgDev? Well, I guess, you both think "both, kind of" aswell.
Thus, if you find it far from realistic to have a unified package it'd be at least nice to have a good level of compatibility. Maybe have PkgTemplates being the template designer with all its customisability and have those templates usable by PkgDev.

> kind of akin to unifying all the packages that provide array types into Arrays.jl.

IMO that's a totally different situation since the likelyhood to need ArrayTypeB when I already have ArrayTypeA is decreasing the more types of arrays I already load while the likelyhood that I want/need PkgDev when I already have PkgTemplates is near to 1 and vice versa.
Said differently, the audience that uses PkgDev and PkgTemplates is called package authors, which is a semi-narrow audience. But what would you call the audience which needs ANY array type? That's an all-but-narrow audience.

**Comment by davidanthoff** [comment]
> The bigger difference between this and PkgButler seems to be that PkgButler isn't really going for customization, whereas that's PkgTemplates' whole shtick.

Yes, the primary target for PkgButler certainly is the 95% of packages that really should just all use exactly the same templates and _not_ fiddle around with weird home grown situations :)

Having said that, I've added a config file now that packages can add to the root and where they can configure certain things. There aren't many options yet, but in principle that options is there now.

In terms of config, my general philosophy was less 100 little knobs that one can change, but rather this idea of "templates" where you can pick one, and then that is just a set of individual config settings. Maybe that could be formalized more in PkgButlerEngine, i.e. to have a set of configs, and then a template is literally just a set of default values for all these config settings.

@rapus95 I think at this point PkgButlerEngine.jl is the only package in the ecosystem that handles updates to packages over their lifetime, so for now that is probably the best place to add extra functionality around that.

**Comment by rapus95** [comment]
It sounds like over time, the two packages might converge. Hopefully 😄 So, rather than reimplementing PkgTemplates.update in here, it might make sense to build upon PkgButlerEngine and add the missing capabilities there. On the other side, it already seems like a good idea to make PkgButlerEngine understand template objects.
After that happened, what would you think about merging into an all-new package (Which indeed might be simply named `PkgButler`)?

**Comment by davidanthoff** [comment]
I'm hesitant to make large changes to PkgButlerEngine in terms of package structure. There is a whole interplay of packages (PkgDev, PkgButlerEngine) and github actions that all play together right now, and something like even just renaming one piece of that is painful and I don't really see the gain.

Having said that, I'm _more_ than open in terms of contributions to PkgButlerEngine, i.e. in terms of what it does. If that means it has to take a dependency on something else I could see that as well.

I also think that I should probably add more package creation stuff. As an end user, I think what I really want is something where I can say "generate a new package from template X", and then an ongoing bot that keeps my package in sync with whatever template X is, in particular if there are updates to template X. That is really the vision for pkg butler, I just haven't gotten to the "generate a new package" part... But all of this is really targeted at the average user, I don't see use cases like Invenia's (where they need to support different source control, CI etc.) as the target for PkgButler right now.

**Comment by rapus95** [comment]
Well, for the CI part, having a a Github CI which runs thests by calling runtests.jl seems to be a good idea even for average users IMO.

**Comment by christopher-dG** [comment]
Sorry for not keeping up with this discussion, I've been on vacation.

I think David has said it pretty well -- PkgButler and company is great for the average case, and when it reaches sufficient maturity, 90% of users could probably use that and be better off for it. PkgTemplates is made to support any workflow, no matter how custom. These custom setups are inherently incapable of being maintained automatically as PkgButler aims to do, so these two packages are just for different use cases and really shouldn't be lumped together.

**Comment by davidanthoff** [comment]
> Well, for the CI part, having a a Github CI which runs tests by calling runtests.jl seems to be a good idea even for average users IMO.

Yes, that is something that is enabled by package butler.

> For the interplay part, if they are strongly entangled, why did you make seperate packages?

They run in different contexts: PkgDev is the package that a user needs on their machine to configure the pkg butler. PkgButlerEngine is the package that runs inside a github action to check whether a package is up-to-date or not. There are some github actions that run the code in PkgButlerEngine on a schedule, and other github actions that are used by the code that is generated by PkgButlerEngine. The split into different packages is motivated by these different run contexts and has worked out really well.

> They need to stay in sync in some sense anyway?

No, there are clear interfaces between them, so they can version independently. But the core structure of which packages exists and what those interfaces are is painful to change.

> maybe having some API/protocol would lower the threshold since you only need to dig into one of the packages since you can rely on having no entanglement aside of the protocol.

That is the design today. If you want to update what the package butler does to a repo, you just make a change to PkgButlerEngine and can ignore everything else.

I agree completely with everything @christopher-dG wrote!

**Comment by christopher-dG** [comment]
I think it's pretty clear that at least for the foreseeable future, both PkgDev and PkgTemplates have their own distinct roles to play.

**Comment by davidanthoff** [comment]
I thought a little more about this, and I have one other idea:

We could add functionality here to PkgTemplate.jl that makes it easy to start a package that is essentially fully configured and set-up to be used with the package butler system and PkgDev.jl. And then I could add a function `PkgDev.generate` that uses PkgTemplates.jl to generate a new package, i.e. essentially `PkgDev.generate` would be a wrapper that calls PkgTemplate with an opiniated set of options that cover the average use-case.

I'll have to think a bit more whether that would actually make things easier or not, and I don't think it would require a lot of coordination, but I think it is worth investigating (which I will do).

**Comment by christopher-dG** [comment]
I think what you want in this case is basically just to provide a specific instance of `Template` that is set up for the PkgButler workflow.

**Comment by christopher-dG** [comment]
Actually, after a brief look at PkgDev/PkgButlerEngine, it seems all you need is a plugin that creates the PkgButler GHA workflow? That would be pretty trivial to implement.

**Comment by davidanthoff** [comment]
Yes, that might well be!
