### ISSUE TITLE
Roadmap to the next release?

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#148]
What are the tasks that are currently blocking the next release?

cc: @christopher-dG

**Comment by christopher-dG** [comment]
Basically just #175. I'll get it done in quarantine.

**Comment by jlperla** [comment]
I am considering the best timing for updating the https://julia.quantecon.org/more_julia/testing.html  notes and a a joint move to suggesting github actions.  Any rough guess on when the new release and features are likely to be pushed?  No pressure, and I wouldn't hold you to any estimates.

**Comment by christopher-dG** [comment]
#145 needs to be reviewed one last time + merged, and #167 needs discussion and possibly merge.
I think if I can get the reviews I need, there could be a new release by the end of this week.

**Comment by christopher-dG** [comment]
New release is queued up!
