### ISSUE TITLE
Failure due to no Git config even with keyword arguments

### ISSUE THREAD

**Issue by ChrisRackauckas** [invenia/PkgTemplates.jl#149]
MWE:

```julia
using PkgTemplates
t = Template(;user="ChrisRackauckas")
generate("testpkg", t)
```

This used to work on Windows where Git shells generally don't exist, but it doesn't seem to work and I can't find out how to fix it with kwargs.

**Comment by christopher-dG** [comment]
I think the prerequisite has always been `user.name` and `user.email` to make commits, PkgTemplates does no Git configuration for you. If you're on 0.6.x you can also just disable Git via `generate(...; git=false)`, or on master you can do `Template(...; disable_defaults=[Git])`.
