### ISSUE TITLE
Changes to file templates based on kwarg (feature request?)

### ISSUE THREAD

**Issue by kescobo** [invenia/PkgTemplates.jl#151]
I'm using the master branch, and so far, seems fantastic. I'm wondering if the following is possible (with apologies if it's obvious - I didn't see it in the docs), and if not, wondering if it can be a feature request.

I'm building a course where each lesson is separate repository (a typical julia package), and they share a number of structural elements. So far, it's really clear that I can use templates/plugins to set up a consistent structure to my liking, which is awesome. The one thing I'd like to do that I don't know how to do is to set up something where I can automatically replace all of a given pattern with another pattern. In particular, I want to change the lesson name throughout. 

So for example, the README.md template might be something like

```
# Lesson {{XX}} - Description of lesson

In Lesson {{XX}}, you will learn how to ...
```

Then the module template might be

```
module Lesson{{XX}}

include("lesson_{{XX}}.jl")
include("assignment_{{XX}}.jl")

end
```

So when I build my template function, it would be need to be able to do something like `my_template("Lesson01"; replacements=(xx=>"01"))`. This is easy enough to do in Atom after the fact, but I thought it might be a bit of a time-saving feature.

**Comment by christopher-dG** [comment]
Thanks for the good explanation! I think some kind of `global_view` keyword would be useful for that.

For now, I think you can use [`user_view`](https://invenia.github.io/PkgTemplates.jl/dev/user/#PkgTemplates.user_view), maybe like this:

```jl
const NeedsNum = Union{Readme, SrcDir}
PkgTemplates.user_view(::NeedsNum, ::Template, pkg::AbstractString) =
    Dict("LESSON" => match(r"(\d+)$", pkg)[1])
```

Then you could use `{{{LESSON}}}` in your template files.

**Comment by christopher-dG** [comment]
Here's a more versatile solution that still uses `user_view` but with a simple custom plugin:

```jl
struct Replacements <: PkgTemplates.Plugin
    d::Dict{String, Any}
end
Replacements(; kwargs...) = Replacements(Dict(string(k) => v for (k, v) in pairs(kwargs)))

PkgTemplates.user_view(::PkgTemplates.Plugin, t::Template, ::AbstractString) =
    PkgTemplates.getplugin(t, Replacements).d

t = Template(; plugins=[Replacements(; LESSON="01")])
```

The one downside is that this approach can't coexist with the one I posted yesterday, i.e. you can't use `user_view` for anything else after you do this.

**Comment by kescobo** [comment]
Awesome, thanks for the explanation! The second one should work, given I didn't know about `user_view` until this :-D.

**Comment by kescobo** [comment]
It's ok with me to close this or leave it open if you want to flag the `global_view` idea
