### ISSUE TITLE
LICENSE files: add "and contributors" to default copyright

### ISSUE THREAD

**Issue by StefanKarpinski** [invenia/PkgTemplates.jl#152]
It's a best practice to include "and contributors" to the copyright statement in a LICENSE file since the copyright of a project does not solely belong to the original author unless the project has a copyright assignment agreement (which is not legal in some countries). I have been manually adding "and contributors" to the copyright line of the LICENSE file whenever I use PkgTemplates to generate a package, but it would arguably be better if that was the default.

**Comment by StefanKarpinski** [comment]
Example: https://github.com/JuliaIO/Tar.jl/commit/5c40343bad36bc0d1f53f594812ec9c84a3c

**Comment by DilumAluthge** [comment]
I 100% agree.

We should make sure to add this to all of the licenses. Of course, most people will use either `MIT` or `ISC`, but I think it will be good for us to just add this to all of the licenses.

**Comment by DilumAluthge** [comment]
In addition to adding this to `PkgTemplates.jl`, we should also add this to other packages that people use to generate new Julia packages.

For example, I think that there is a `PkgSkeleton.jl`.

Also, we should add this change to the Pkg Butler stuff from @davidanthoff

**Comment by DilumAluthge** [comment]
One last thought: currently, none of my personal Julia packages or organization Julia packages have the "and contributors" language.

It would be really cool to have an automated tool that can go through all of my packages (both in my personal account and also in organizations that I own) and make PRs to add this language to the license files.

**Comment by StefanKarpinski** [comment]
Here's the thing though: it should probably be the person who is attributed in the copyright line themselves who do this. But I guess as long as they do the merging that's good enough.

**Comment by DilumAluthge** [comment]
> Here's the thing though: it should probably be the person who is attributed in the copyright line themselves who do this. But I guess as long as they do the merging that's good enough.

Yeah, we would only open pull requests. It would be up to the author to merge those pull requests.

**Comment by christopher-dG** [comment]
I'm cool with adding this to PkgTemplates but I don't really feel like doing another round of automated PRs myself this time around :sweat_smile:.

**Comment by StefanKarpinski** [comment]
I think gating this change on making a bunch of PRs is counterproductive. Let's fix the default now. If someone wants to make PRs, they can do so at any point.

**Comment by DilumAluthge** [comment]
> I think gating this change on making a bunch of PRs is counterproductive. Let's fix the default now. If someone wants to make PRs, they can do so at any point.

Agree.
