### ISSUE TITLE
Make the next breaking release 1.0.0?

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#168]
The latest stable release of PkgTemplates is 0.6.4.

Instead of making the next breaking release 0.7.0, what do you think about making it 1.0.0?

cc: @christopher-dG

**Comment by christopher-dG** [comment]
I think I want to be able to break stuff one more time before 1.0, just in case there's some common complaint about 0.7. If 0.7 goes smoothly, it'll certainly go to 1.0 next (and potentially without any updates).

**Comment by christopher-dG** [comment]
Gonna close this, 0.7 is being released and we'll go ahead with 1.0 soon-ish.
