### ISSUE TITLE
GitLab pages GitLab CI job hangs

### ISSUE THREAD

**Issue by xlxs4** [invenia/PkgTemplates.jl#170]
### Reproducing

Have a template set up with every default as it is and GitLab pages the only plugin. Push to GitLab and wait. After `test` and the initial `pages` job successfully conclude, a new `external` job spawns named `pages:deploy`.  The job gets `retried` quickly (sub-minute quickly), this occurs 2 or 3 more times with the end result being something like this:

![image](https://user-images.githubusercontent.com/54778816/82042732-1262d200-96b3-11ea-9cbb-eec3a09872f3.png)

### Description

GitLab CI jobs triggered after pushing templates generated hang (indefinitely?). 
After some debugging and playing around, it seems that only the GitLab pages deployment is problematic. All other plugins (AppVeyor, Coverage, GitLab CI...) seem to work as intended. Same issue occurs while using both latest (not stable) 0.6.4 release and in stable 0.6.3. I haven't tried passing additional assets to `Documenter` while creating the template, I went for the default `None` value. I also tried to mimic what Papp proposed in his "demo repo" [here](https://gitlab.com/tkpapp/GitlabJuliaDemo.jl) to no avail.

Of course, this might not be relevant to PkgTemplates, and GitLab could be at fault. Specifically, it could be related to [other similar issues](https://gitlab.com/gitlab-com/support-forum/-/issues/771#note_130802955) (or even to [yesterday's incidents](https://gitlab.com/gitlab-com/gl-infra/production/-/issues/2139))

Let me know if you need any additional info.
Sorry in advance if I'm being stupid with this, I'm a novice 😄

**Comment by christopher-dG** [comment]
Can you try it on master branch? (The bit about 0.6.3 being the stable release is outdated, but there are no changes to GitLab in 0.6.4 anyways)

**Comment by xlxs4** [comment]
I did, same results

**Comment by christopher-dG** [comment]
Link to the repo please?

**Comment by xlxs4** [comment]
It was a test repo so I could experiment with the package, so I made one anew and reproduced... or so I thought :P 
It works now as intended. I guess it's on GitLab's side
Feel free to close and thanks for the timely assistance

**Comment by christopher-dG** [comment]
Sounds good 🙂
