### ISSUE TITLE
Strip `"`s in user entries?

### ISSUE THREAD

**Issue by mbauman** [invenia/PkgTemplates.jl#184]
Ok, so this one totally qualifies as a PEBCAK error, but somehow I thought that my values needed to be protected in `"`s based upon how the defaults were printed. I figured I'd report my mishap here as it might happen to others too... and is part of the problem in #183.

Perhaps there's another way to describe/delimit the default values (e.g., with color)?  Or perhaps you could explicitly ignore `"`s (or whatever delimiter you use in the printout).

Here's one particularly funny example of how this went wrong:

```
Enter value for 'dir' (String, default="~/.julia/dev"): "."
...
[ Info: New package is at /Users/mbauman/Projects/"."/NewPackage
```

**Comment by christopher-dG** [comment]
Yeah the default printing can definitely be a point of confusion. I don't see any cases where input should actually contain quotes, so it seems like a good idea to strip them.
