### ISSUE TITLE
Is it possible not to remove '.jl' in pkg string?

### ISSUE THREAD

**Issue by htyeim** [invenia/PkgTemplates.jl#196]
the related code is at https://github.com/invenia/PkgTemplates.jl/blob/master/src/template.jl#L123

`endswith(pkg, ".jl") && (pkg = pkg[1:end-3])`

If I add a package, I would like that the package can be inited exactly at the directory I want.
So I don't if it is a good to remove this line.

**Comment by christopher-dG** [comment]
I don't think I'm going to change this behaviour, it's a helpful safeguard against accidentally creating invalid packages. You can create a plugin that moves your package from `path` to `path.jl` easily enough though.

**Comment by htyeim** [comment]
Got it. Thanks~

**Comment by christopher-dG** [comment]
Here's an example:

```jl
using PkgTemplates
struct MoveJL <: PkgTemplates.Plugin end
PkgTemplates.posthook(::MoveJL, ::Template, pkg_dir::AbstractString) = mv(pkg_dir, pkg_dir * ".jl")
PkgTemplates.priority(::MoveJL, ::typeof(PkgTemplates.posthook)) = typemin(Int)

julia> t = Template(; dir="/tmp", plugins=[MoveJL()]);

julia> t("Hello")
# ...

julia> isdir("/tmp/Hello.jl")
true

julia> isdir("/tmp/Hello")
false
```

**Comment by htyeim** [comment]
Thank you very much! I used `mv` directly 🤣 as I don't know how to use Plugin.
