### ISSUE TITLE
repr(Documentor) not evalable

### ISSUE THREAD

**Issue by oxinabox** [invenia/PkgTemplates.jl#197]
I was following instructions on saving via using `show`
and then i `include`ed the file i created and i got an error because Documentor doesn't define the default constructor,
and thus can't be constructed with its positional arguments

It made for me:
```julia
Documenter{GitHubActions}(String[], Dict{Symbol,Any}(), PkgTemplates.github_pages_url, "/Users/oxinabox/.julia/packages/PkgTemplates/7Erns/templates/docs/make.jl", "/Users/oxinabox/.julia/packages/PkgTemplates/7Erns/templates/docs/src/index.md"),
```

trying to run that gives:
```
ERROR: MethodError: no method matching Documenter{GitHubActions}(::Array{String,1}, ::Dict{Symbol,Any}, ::typeof(PkgTemplates.github_pages_url), ::String, ::String)
```

**Comment by christopher-dG** [comment]
I'll look at this in a bit, i think the inner constructor just needs to be moved outside.
