### ISSUE TITLE
Add option to Tests() to skip [extras]

### ISSUE THREAD

**Issue by schlichtanders** [invenia/PkgTemplates.jl#200]
Even if you configure Tests(project=true), PkgTemplates inserts the tests dependencies in the old way too.

```
[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```

I see that this is wanted as a default for backwards compatibility, however someones like me rather prefer to have the cleaner style and break with backwards compatibility for the sake of simplicity.

It would be great, if an option could be added to skip these

**Comment by christopher-dG** [comment]
Are you sure about this? I can't reproduce.

```jl
julia> using PkgTemplates

julia> t = Template(; julia=v"1.4", plugins=[Tests(; project=true)]);

julia> t("Hello")
[ Info: Running prehooks
[ Info: Running hooks
 Activating new environment at `~/code/Hello/test/Project.toml`
   Updating registry at `~/.local/share/julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
   Updating `~/code/Hello/test/Project.toml`
  [8dfed614] + Test
   Updating `~/code/Hello/test/Manifest.toml`
  [2a0f44e3] + Base64
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [9a3f8284] + Random
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
 Activating environment at `~/.local/share/julia/environments/v1.4/Project.toml`
[ Info: Running posthooks
[ Info: New package is at /home/degraafc/code/Hello

shell> cat ~/code/Hello/Project.toml
name = "Hello"
uuid = "7ee7a956-86f9-4d77-b172-54829c3bb4a9"
authors = ["Chris de Graaf <me@cdg.dev> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"
```

**Comment by schlichtanders** [comment]
thank you very much for trying it on your side! I guess it has something to do with me not providing `[compat]`, i.e. as soon as I support 1.0 the `[extras]` kick in, at least that would be my guess...

I will write as soon as I tried it out and know for sure what is going on

**Comment by schlichtanders** [comment]
cannot replicate it again on my side. Don't know what it was.

Thanks a lot for pointing out that this should already be supported!
