### ISSUE TITLE
Make TagBot use the `DOCUMENTER_KEY` by default

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#206]
If the user does not specify an SSH deploy key, can we make TagBot use the `DOCUMENTER_KEY` by default?

It is becoming increasingly common for people to ask questions like "where is the doc build for my tag v1.2.3" and "where is my `stable` doc build". The context is usually that they are using GitHub Actions CI to build their Documenter docs.

cc: @christopher-dG 
cc: @timholy

**Comment by DilumAluthge** [comment]
I'm happy to make the PR, but I will need some guidance.

**Comment by christopher-dG** [comment]
Yeah, this seems like a fine idea. All you need to do is change the default `ssh` to `Secret("DOCUMENTER_KEY")`

https://github.com/invenia/PkgTemplates.jl/blob/4a5de3f79024a3c8c4091d8bca1e93836f23366c/src/plugins/tagbot.jl#L42
