### ISSUE TITLE
Fresh packages on Windows contain useless directory/symlink _git2_*

### ISSUE THREAD

**Issue by SaschaMann** [invenia/PkgTemplates.jl#211]
When I generate a new package on Windows, the folder contains a broken symlink with the name `_git2_*`, e.g. `_git2_a11248: broken symbolic link to testing`

Likely due to this issue: https://github.com/libgit2/libgit2/issues/5147

Later versions of libgit2 don't contain that issue anymore, could the version that PkgTemplates uses be updated to resolve this?

**Comment by DilumAluthge** [comment]
I think the PkgTemplates just uses the LibGit2 that Julia provides.

**Comment by christopher-dG** [comment]
> I think the PkgTemplates just uses the LibGit2 that Julia provides.

Correct.

I added a "fix" to #208, hopefully that works.
