### ISSUE TITLE
Tag a new release for Julia 0.7/1.0

### ISSUE THREAD

**Issue by scls19fr** [invenia/PkgTemplates.jl#22]
Hello,

I noticed that CI is running fine for Julia 0.7/1.0 but latest tagged version was 7 Dec 2017 (and so was probably only for Julia 0.6)
It will be nice if you could tag a new release with Julia 0.7/1.0 support

Kind release

**Comment by christopher-dG** [comment]
#20 will be merged this week, I'll release at that point :slightly_smiling_face:.

**Comment by christopher-dG** [comment]
I've just tagged a new release, it'll be put into metadata soon enough 🙂.

**Comment by scls19fr** [comment]
Thanks @christopher-dG
