### ISSUE TITLE
Should default `.gitignore` have `/Manifest.toml`  instead of `Manifest.toml`?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/PkgTemplates.jl#220]
The default `.gitignore` will ignore `Manifest.toml` files
```julia
julia> Template(dir=".")("demo.jl")
[ Info: Running prehooks
[ Info: Running hooks
 Activating environment at `~/repos/demo/Project.toml`
   Updating registry at `~/.julia/registries/General`
No Changes to `~/repos/demo/Project.toml`
No Changes to `~/repos/demo/Manifest.toml`
 Activating environment at `~/repos/Project.toml`
[ Info: Running posthooks
[ Info: New package is at /Users/nick/repos/demo

shell> cat ./demo/.gitignore
Manifest.toml
```
But many repos choose to commit (not ignore) `docs/Manifest.toml`, and so would prefer to only ignore `/Manifest.toml`. In fact, PkgTemplates itself does this:
https://github.com/invenia/PkgTemplates.jl/blob/97a062fd4fb798e1172149843d7098e5ec3ba619/.gitignore#L5

I couldn't see an easy way to override this either, e.g. `Git(ignore=["/Manifest.toml"])` results in having `/Manifest.toml` _and_ `Manifest.toml` in the `.gitignore`

Can we change the default to `/Manifest.toml`? 
Alternatively, can we expose an easy way to change this (if there's not one already)?

**Comment by nickrobinson251** [comment]
> I couldn't see an easy way to override this

Actually, the override seems to be to pass `Template(; plugins=[Git(ignore=["/Manifest.toml"], manifest=true)])`

**Comment by nickrobinson251** [comment]
Actually, i'm confused if about whether the current behaviour (adding `Manifest.toml` instead  of `/Manifest.toml`) is even intended:
in `gitignore(p::Git)` we have
https://github.com/invenia/PkgTemplates.jl/blob/97a062fd4fb798e1172149843d7098e5ec3ba619/src/plugins/git.jl#L43-L45

but in `hook(::Git, args...)`  we have
https://github.com/invenia/PkgTemplates.jl/blob/97a062fd4fb798e1172149843d7098e5ec3ba619/src/plugins/git.jl#L93-L96

**Comment by christopher-dG** [comment]
Ah yeah, I think this is a bug, we should just have:

```jl
gitignore(p::Git) = p.gitignore
```

And then when `manifest=false`, the `/Manifest.toml` (root manifest only) will be correctly added.
