### ISSUE TITLE
How to specify logo for use by Documenter plugin?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/PkgTemplates.jl#221]
specifically, i believe a logo is an assets that should _not_  get added to the `HTML` in `makedocs` in `docs/make.jl`

- i'd like to include a `.png` logo in the docs
- to do this i think we need
  1. the `png` to exist  in `docs/src/assets/logo.png`
  2. the `.png` must  _not_ be mention in the `assets` in`makedocs(; format=Documenter.HTML(; assets=[...]), ...)` (as this seems to make Documenter unhappy, and causes `make.jl` to error with `ERROR: LoadError: Unrecognised asset class unknown for `assets/logo.png`. I think this is intended behaviour.)

Using `Documenter{GitLabCI}(assets=["foo.ext"])` adds `"foo.ext"` to `assets` in `HTML`/`makedocs`.

Quoting the [Documenter.HTML  docs](https://juliadocs.github.io/Documenter.jl/dev/lib/internals/writers/#Documenter.Writers.HTMLWriter.HTML):
> For the logo, Documenter checks for the existence of assets/logo.{svg,png,webp,gif,jpg,jpeg}, in this order. The first one it finds gets displayed at the top of the navigation sidebar. It will also check for assets/logo-dark.{svg,png,webp,gif,jpg,jpeg} and use that for dark themes.

**Comment by christopher-dG** [comment]
So if I'm reading this correctly, the fix is to offer a `logo` keyword to `Documenter`, then copy that file into the assets directory but not include the logo file in the `assets` value to `makedocs`?
