### ISSUE TITLE
Option to skip remote creation in Git

### ISSUE THREAD

**Issue by aminya** [invenia/PkgTemplates.jl#224]
Having an option to skip remote creation in Git is necessary. That should be the default behavior IMO, but I am OK with an opt-in option too.

From the old issue that was discussed in the old PR 😄 

Copying the comments:

- https://github.com/invenia/PkgTemplates.jl/pull/61#issuecomment-544208700:
Something strange happens when I try to publish a repository that is generated by this package:
![image](https://user-images.githubusercontent.com/16418197/67152979-c7144c80-f2a6-11e9-80b5-8f81bb08cec2.png)

- https://github.com/invenia/PkgTemplates.jl/pull/61#issuecomment-544689505
> Did you create a repository on GitHub before trying to push to it?

In Github Desktop, there is an option to **publish** a repository into cloud. Publishing works for other local repositories, but it doesn't work for repositories created by PkgTemplates

- https://github.com/invenia/PkgTemplates.jl/pull/61#issuecomment-544787816:

Turns out GitHub Desktop just isn't that smart... It assumes that if a remote exists, then the repo must already exist upstream. Which makes sense when people are using GitHub Desktop for everything, but that's far from universal.

I'm inclined to not do anything about this because:
a) this is Desktop's weird behaviour, not ours
b) in the near(?) future, PkgTemplates will offer to create the repo for you

- GitHub Desktop issue:
https://github.com/desktop/desktop/issues/8507
https://github.com/desktop/desktop/issues/5491

**Comment by christopher-dG** [comment]
My take on this is still https://github.com/invenia/PkgTemplates.jl/pull/61#issuecomment-544800708, since I don't think anyone else is really running into this.

> A simpler alternative would be to create a plugin whose posthook removed the remote.

**Comment by aminya** [comment]
I am OK with whatever solution that solves the issue. You know the codebase, so I'll let you decide on the best solution.

**Comment by christopher-dG** [comment]
This solution is to let you write your own personal solution 😅 

Here's a plugin you can use (although you'll have to wait until #225 is in to use it):

```jl
using LibGit2, PkgTemplates
struct RemoveRemote <: PkgTemplates.Plugin end
PkgTemplates.posthook(::RemoveRemote, ::Template, pkg_dir) =
    LibGit2.with(r -> LibGit2.remote_delete(r, "origin"), GitRepo(pkg_dir))
```

**Comment by aminya** [comment]
That works for me. 

- Some people don't plan to make a remote for their Julia packages. Not everyone plans to make their code opensource. That includes many companies or enterprises. An option for not having `remote` is very reasonable. 

- GitHub desktop is a major Git client with 10,000 stars, and there will be people who will run into this issue.

**Comment by christopher-dG** [comment]
> Some people don't plan to make a remote for their Julia packages. Not everyone plans to make their code opensource. That includes many companies or enterprises.

A remote existing and not being used isn't harmful, and I'd argue that > 95% of people are pushing their code *somewhere* (public or private).

> The remote now defaults to GitHub with no option to change that.

The remote host is customizable with the `host` keyword to `Template`, the default exists to serve the majority of users

> GitHub Desktop is a major Git client with 10,000 stars, and there will be people who will run into this issue.

If we find more people who are using Desktop and running into this I'll happily revisit, but until then I'd rather not work around other software's problems. Maybe I'll look into submitting a PR to Desktop.
