### ISSUE TITLE
How to add custom badge?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/PkgTemplates.jl#227]
I'd like to add the ability to generate a repo with both
- a [BlueStyle badge](https://github.com/invenia/BlueStyle#code-style-badge)
- a [ColPrac badge](https://github.com/SciML/ColPrac#marking-a-repository-as-following-colprac)

AFAICT, badges are added to the README via `badges(::Plugin)`, but it's not clear how to have additional badges not connected to a `Plugin`

Does one have to implement a `Plugin`? e.g.
```julia
struct BlueStyleBadge <: Plugin end
badges(::BlueStyleBadge) = Badge(
    "Code Style: Blue",
    "https://img.shields.io/badge/code%20style-blue-4495d1.svg",
    "https://github.com/invenia/BlueStyle"
)
```

**Comment by christopher-dG** [comment]
Yeah, you just write a one liner plugin like you did.
