### ISSUE TITLE
Run TagBot and CompatHelper at random times?

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#229]
Right now, the default TagBot and CompatHelper templates will run every day at 00:00 UTC.

Instead, what if we made those templates run at a random hour and minute?

I.e. instead of this:
```
cron: 0 0 * * *
```

What if we had this?
```
cron: $(rand(0:59) $(rand(0:23)) * * *
```

@christopher-dG

**Comment by DilumAluthge** [comment]
This way, each time you run `generate(my_template, "MyPackageName")`, it picks a different hour and minute for TagBot, CompatHelper, etc.

So then, in the ecosystem, we can get packages running at different times, instead of all at the same time.

**Comment by christopher-dG** [comment]
Sorry this slipped under my radar for so long.

Personally I don't really like this idea. I much prefer things to be consistent and predictable, and I feel like people are going to wonder what the significance of the numbers are if they see weird ones. It's not like we're bringing GitHub down every hour/day either.

And if you want that for yourself, you can always pass your own `cron` keyword to those plugins.
