### ISSUE TITLE
[Suggestion] Add `DocMeta.setdocmeta!(PkgName, :DocTestSetup, :(using PkgName); recursive=true)` by default

### ISSUE THREAD

**Issue by terasakisatoshi** [invenia/PkgTemplates.jl#232]
As described in [the documentation of Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Module-level-metadata),
it is a good idea to add, by default, the expression `DocMeta.setdocmeta!({{{PKG}}}, :DocTestSetup, :(using {{{PKG}}}); recursive=true)` before `doctest({{{PKG}}})`
or inside of `make.jl` i.e.

```julia
using {{{PKG}}}
using Documenter

DocMeta.setdocmeta!({{{PKG}}}, :DocTestSetup, :(using {{{PKG}}}); recursive=true)

makedocs(;
    modules=[{{{PKG}}}],
...
...
...
```

This is required if one wants to run doctest of methods defined in one's Package (Say `PkgName` for example).

Assume `PkgName.jl` has a `domath` function (see the code below):

`````julia
module PkgName

"""
    domath(x::Number)
Return `x + 5`.

```jldoctest
julia> domath(3)
8
```

"""
domath(x::Number) = x + 5

export domath

end
`````

Both following commands will fail with a message `ERROR: UndefVarError: domath not defined`
if `DocMeta.setdocmeta!(PkgName, :DocTestSetup, :(using PkgName); recursive=true)` is missing.
`

```console
$ julia --project=docs docs/make.jl
```

```console
$ julia --project=docs -e '
  using Documenter: doctest
  using PkgName
  doctest(PkgName)'
```

Any ideas ?

**Comment by christopher-dG** [comment]
I didn't know this existed, it looks really useful! A PR would be welcome. 🙂

**Comment by simeonschaub** [comment]
> Both following commands will fail with a message `ERROR: UndefVarError: domath not defined`
> if `DocMeta.setdocmeta!(PkgName, :DocTestSetup, :(using PkgName); recursive=true)` is missing.
> `
> 
> ```
> $ julia --project=docs docs/make.jl
> ```
> 
> ```
> $ julia --project=docs -e '
>   using Documenter: doctest
>   using PkgName
>   doctest(PkgName)'
> ```
> 
> Any ideas ?

Yes, the second example is not using `docs/make.jl` at all, so you either need to do `DocMeta.setdocmeta!` there as well, or figure out a way to pass an argument to `make.jl`, that will make it run only the doctest.

**Comment by terasakisatoshi** [comment]
Thank you everyone. 

I'll make a PR to add

`DocMeta.setdocmeta!({{{PKG}}}, :DocTestSetup, :(using {{{PKG}}}); recursive=true) before doctest({{{PKG}}})`

(and also modify test script to pass this PR)
