### ISSUE TITLE
Add to an older package?

### ISSUE THREAD

**Issue by timholy** [invenia/PkgTemplates.jl#234]
I have an old "package," https://github.com/timholy/DebuggingUtilities.jl, and it would be nice to add GitHubActions support to it using PkgTemplates. For example:

```julia
using PkgTemplates
t = Template(plugins=[GitHubActions()])
t("DebuggingUtilities"; extend=true)
```

Currently I do that by creating a junk package and then manually copying configuration files, then deleting the junk package.

**Comment by christopher-dG** [comment]
Dupe of #16, this has been long desired 😅

**Comment by timholy** [comment]
Ah, thanks, sorry for the duplicate!
