### ISSUE TITLE
MIT License not recognized

### ISSUE THREAD

**Issue by bdvalqui** [invenia/PkgTemplates.jl#259]
I am creating a package with the following code:

using PkgTemplates
t=Template(;
    user="bdvalqui",
    license="MIT",
    authors=["Brayam Valqui"],
    plugins=[
        TravisCI(),
        Codecov(),
        Coveralls(),
        AppVeyor(),
            ],
      )
t("Test2")

I got the following message:

┌ Warning: Unrecognized keywords were supplied, see the documentation for help
│   kwargs =
│    Dict{Symbol,Any} with 1 entry:
│      :license => "MIT"

Do you know what should I write in license? Thanks.

Brayam

**Comment by christopher-dG** [comment]
https://invenia.github.io/PkgTemplates.jl/stable/user/#PkgTemplates.License

If you wanted to customize the license you would do:

```jl
t = Template(; plugins=[License(; name="FOO")]
```

But MIT is already the default so you don't actually have to do anything.
