### ISSUE TITLE
.jl suffix removed

### ISSUE THREAD

**Issue by mzgubic** [invenia/PkgTemplates.jl#267]
```
julia> t = Template()

julia> t("ExamplePackage.jl")
```

Creates a package called `ExamplePackage` (no `.jl`). Is this intentional? Why?

It looks intentional
https://github.com/invenia/PkgTemplates.jl/blob/238bfc11c037f341eff4889e0424a66d1edf7404/src/template.jl#L123

**Comment by christopher-dG** [comment]
Yes, this is intentional. You can't have a package with `.jl` in the actual name, it's just a convention for remote repo URLs.
