### ISSUE TITLE
dev_dir should respect JULIA_PKG_DEVDIR

### ISSUE THREAD

**Issue by fredrikekre** [invenia/PkgTemplates.jl#28]
https://github.com/invenia/PkgTemplates.jl/blob/07e2277a17a86fff814d5a6b90f915f9e17db8a1/src/template.jl#L6
should use `JULIA_PKG_DEVDIR`, or call https://github.com/JuliaLang/Pkg.jl/blob/2039662ad21186767e58086f1cc349432bf2611e/src/Pkg.jl#L21 directly.

**Comment by christopher-dG** [comment]
Thanks for pointing this out, I wasn't aware that the function in Pkg existed!
