### ISSUE TITLE
Could you please add the ISC license as an option?

### ISSUE THREAD

**Issue by juliohm** [invenia/PkgTemplates.jl#3]
You can find the license here: https://github.com/JuliaLang/PkgDev.jl/blob/master/res/licenses/ISC

**Comment by bramtayl** [comment]
Do you think the ISC license is better than the MIT license? I could just replace it; the overall philosophy of this package is to use the best defaults for beginners.

**Comment by bramtayl** [comment]
Shoot sorry I subscribed to this repo and got an email and without thinking thought it was for pacakgegenerator

**Comment by juliohm** [comment]
Oh, got it, thought you were talking about this repo @bramtayl.

@christopher-dG could you please consider this change?

**Comment by christopher-dG** [comment]
I see no reason not to add it, I'll get right on that. 

But I'm going to hold off on making it the default, at least until ISC becomes more commonly used (I'm aware that this is kind of a paradox). I think there's value in MIT's popularity; people know the terms as soon as they see the MIT label on a repo so there's no actual need for them to read the license.

**Comment by juliohm** [comment]
Thanks @christopher-dG! I appreciate it.
