### ISSUE TITLE
Using Template makes a git remote that uses HTTPS instead of SSH

### ISSUE THREAD

**Issue by HettieC** [invenia/PkgTemplates.jl#355]
I have used ```Template(interactive=true)("MyPkg")``` to make a package, and I then set the directory. When I then try to push to github I am asked for username and password, which can't be used anymore as github now requires the use of an SSH key. 
You can get round this by going into the directory and using 
```git remote remove origin```
```git remote add origin git@github.com:HettieC/MyPkg.git``` 
but it would be preferred to not have to perform this extra step.

**Comment by nickrobinson251** [comment]
You can set the remote to use ssh by customising the `Git` plugin (which is a plugin included in the `Template` by default) and setting `ssh=true`

e.g. 
```julia
julia> tpl = Template(plugins=[Git(ssh=true)]);

julia> tpl("MyPkg")
```
or in interactive mode
```julia
julia> tpl = Template(interactive=true);
...
Git keywords to customize:
[press: d=done, a=all, n=none]
   [ ] branch
   [ ] email
   [ ] gpgsign
   [ ] ignore
   [ ] jl
   [ ] manifest
   [ ] name
 > [X] ssh
Enter value for 'ssh' (Bool, default=false): true
...

julia> tpl("MyPkg")
```

Then you should see something like
```julia
~> cd ~/.julia/dev/MyPkg/                                                                                                                 
~/.j/d/MyPkg> git remote -v                                                                                                               
origin  git@github.com:nickrobinson251/MyPkg.jl.git (fetch)
origin  git@github.com:nickrobinson251/MyPkg.jl.git (push)
```

Does that resolve the issue? Do you think there's something we could do to make the ssh option easier or clearer?

**Comment by HettieC** [comment]
That does resolve it, but seeing as Git no longer supports password authentication I'd have said it would be beneficial to make SSH the default, to avoid having to go through and change anything. 

You also need to specify an ssh value when doing the above way, but just usual the defaults and not customising Git is able to produce an automatic HTTPS link.

It's not a huge issue, but takes some digging to find out what's going wrong with Git, and then starting over.

**Comment by nickrobinson251** [comment]
> seeing as Git no longer supports password authentication I'd have said it would be beneficial to make SSH the default

That's a fair point, though as far as I can tell GitHub still recommends HTTPS (with a PAT) and that's the default for `git clone`, so I don't think will change the default here.
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
