### ISSUE TITLE
Question to your docs workflow

### ISSUE THREAD

**Issue by famura** [invenia/PkgTemplates.jl#366]
Hi there,

I am new to Julia and curious why you run `doctests` explicitly (see [here](https://github.com/invenia/PkgTemplates.jl/blob/bdb157ef8440dc493644c1915e6488c5eaad5204/.github/workflows/CI.yml#L107)). When I run `julia --project=docs docs/make.jl` locally it (amongst other things) prints `[ Info: Doctest: running doctests.` What am I missing?

Best regards,
Fabio

**Comment by nickrobinson251** [comment]
looks like @fchorney added this -- Fernando, do you remember why we did it this way?

**Comment by iamed2** [comment]
I believe this was actually added in https://github.com/invenia/PkgTemplates.jl/pull/201, which explains the reasoning.

**Comment by nickrobinson251** [comment]
Thanks, Eric! Let us know if that link doesn't answer your question, @famura :)
