### ISSUE TITLE
Wanna take the code from OnlinePackage? (plugin service integrations)

### ISSUE THREAD

**Issue by bramtayl** [invenia/PkgTemplates.jl#46]
I've been working on [OnlinePackage](https://bramtayl.github.io/OnlinePackage.jl/dev/) and recently significantly pared it down and refactored it. It runs pretty quick and I've finally figured out a way to effectively test it on CI. I created a fake GitHub account called OnlinePackage connected to a fake email (there was probably a better way to do this but...). It does all the online work you'd really need to do to set up a package with automatically syncing docs. I figured it would fit in really nicely as part of the pipeline here and tbh I'm kinda bored of maintaining the code.

**Comment by christopher-dG** [comment]
Yeah, I think this would be a good idea. I'll see when I have time to integrate it :slightly_smiling_face:.

**Comment by christopher-dG** [comment]
I'll close this now since there's a relevant PR open.
