### ISSUE TITLE
Add interactively_generate("MyPkg") function?

### ISSUE THREAD

**Issue by juliohm** [invenia/PkgTemplates.jl#5]
What do you think of

```julia
interactively_generate(pkg::String) = generate(pkg, interactive_template())
```

I always call these two commands one after the other. This would save some typing and memorization of function names.

**Comment by christopher-dG** [comment]
This is a good idea. Another thing you may want to consider is adding a template to your `.juliarc.jl` if you tend to use the same one over and over.

**Comment by christopher-dG** [comment]
There is the safe but painfully slow way:

```julia
const PKG_TEMPLATE = if Pkg.installed("PkgTemplates") != nothing
    using PkgTemplates
    Template(; ...)
else
    warn("PkgTemplates is not installed; could not initialize PKG_TEMPLATE")
end
```

Or the fast and dangerous way:

```julia
using PkgTemplates  # Assumes it's installed.
const PKG_TEMPLATE = Template(; ...)
```

You could also experiment with serializing a template and deserializing it when Julia starts; I'm not sure if that would be faster but it's definitely the least reliable of the options if you ever use different versions of Julia.

**Comment by juliohm** [comment]
Yes, I like the `generate_interactive` option already. I am not generating packages everyday to have it in my .juliarc.jl :) The slow down in the start up is not worth it.

**Comment by christopher-dG** [comment]
I agree! I am tempted to create some kind of "preferences" structure to save default values for `Template`'s kwargs to make the process even faster.
