### ISSUE TITLE
Retroactively run plugins in packages

### ISSUE THREAD

**Issue by christopher-dG** [invenia/PkgTemplates.jl#65]
I'll often create a package with only the TravisCI plugin or without a template altogether, and later when it matures a little I want to integrate Documenter. When that happens, I usually copy over some other project's doc setup which is less than ideal.
It would be nice to be able to make a plugin work on an already-existent repository.

This isn't trivial though:
- Plugins can operate on shared files. During package generation we have knowledge of all the enabled plugins, but in this case we wouldn't.
- Any previous manual editing of existing generated files could mess things up.

Somewhat similar to #16.

**Comment by kskyten** [comment]
How about applying the templates to a different branch and let git handle the diffing?

**Comment by christopher-dG** [comment]
yeah turns out this is the exact same as #16
