### ISSUE TITLE
Documenter assets API has changed

### ISSUE THREAD

**Issue by harryscholes** [invenia/PkgTemplates.jl#69]
I just hit the following error in a new package:

```julia
ERROR: LoadError: TypeError: in keyword argument assets, expected Union{Nothing, Array{#s105,1} where #s105<:AbstractString}, got Array{Any,1}
Stacktrace:
 [1] (::getfield(Documenter, Symbol("#kw##makedocs")))(::NamedTuple{(:modules, :format, :pages, :repo, :sitename, :authors, :assets),Tuple{Array{Module,1},Documenter.Writers.HTMLWriter.HTML,Array{Pair{String,String},1},String,String,String,Array{Any,1}}}, ::typeof(makedocs)) at ./none:0
 [2] top-level scope at none:0
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] include(::String) at ./client.jl:403
 [7] top-level scope at none:0
```

https://github.com/invenia/PkgTemplates.jl/blob/901a0a3d7139588819bad19acfc891a63bda7637/src/plugins/documenter.jl#L80-L94

To fix, I had to provide the `assets` as a kwarg to `Documenter.HTML()` as a `String[]`.

e.g.

```julia
makedocs(;
    modules=[EffectSizes],
    format=Documenter.HTML(assets=String[]),
    pages=[
        "Home" => "index.md",
    ],
    ...
```

**Comment by christopher-dG** [comment]
Ah, I believe there is some probably some other fixes for Documenter that need to be done. I'll make sure that it's working properly in #61 before merging that.

**Comment by mortenpi** [comment]
This is actually also a slightly suboptimal deprecation on our part. `assets = []` used to be allowed, but the type signature is stricter now. Ideally though, if you don't have any assets, you would not specify the `assets` keyword at all.

Slightly related: we are now making breaking changes and introducing deprecations between 0.x versions in Documenter. Would it be helpful if we'd give you a heads up before tagging a release?

**Comment by christopher-dG** [comment]
> Ideally though, if you don't have any assets, you would not specify the assets keyword at all.

This is correct, I'll make that change for when there are no assets.

> Would it be helpful if we'd give you a heads up before tagging a release?

Yeah, certainly! Feel free to just ping me on Slack, in a commit comment, etc.

**Comment by christopher-dG** [comment]
Closing, as this bug is fixed in the current release and the coming-soon #61 uses the latest Documenter API.
