### ISSUE TITLE
Use Mustache for docs/ and test/?

### ISSUE THREAD

**Issue by tkf** [invenia/PkgTemplates.jl#72]
It would be nice if it is possible to tweak templates for `docs/make.jl`, `docs/src/index.md`, and `test/runtests.jl`.

For example, I often [make `docs/make.jl` an "sandboxed executable"](https://github.com/tkf/Transducers.jl/blob/95520f0cb719827130eac7e912a7ec9d75e3e470/docs/make.jl#L1-L11) which makes the Travis setup as trivial as [`script: docs/make.jl`](https://github.com/tkf/Transducers.jl/blob/95520f0cb719827130eac7e912a7ec9d75e3e470/.travis.yml#L25).  Also, I want to wrap code in `test/runtests.jl` as a module to make the test reproducible in REPL.  I'd like to use those settings from the get-go.  However, it is not easy to do this at the moment.

**Comment by christopher-dG** [comment]
When #61 is done (soon I hope) you should be able to do this.
