### ISSUE TITLE
Don't add the generated project as a dependency

### ISSUE THREAD

**Issue by kskyten** [invenia/PkgTemplates.jl#78]
When I generate a project with PkgTemplates, the generated project gets added to the Project.toml file of the current environment as a dependency. This will sometimes prevent adding other packages as the dependencies cannot be resolved. Is there an option to stop this from happening?

**Comment by christopher-dG** [comment]
This is already optional in a separate branch (which I should really get around to finishing up). I'll cherry pick it and make a patch release.
