### ISSUE TITLE
Proposal: Repo Creation from Interactive Template

### ISSUE THREAD

**Issue by arnavs** [invenia/PkgTemplates.jl#84]
The biggest pain point for me is having to go to GitHub's website to create the (empty) repo, before populating it with `PkgTemplates.`

There is a nice API for doing this from the command line; i.e., I could run `curl -u 'arnavs' https://api.github.com/user/repos -d '{"name":"SomePackage.jl"}'`, and it would prompt me to enter my GitHub credentials. 

Would it make sense to integrate this into the interactive template generator? Or, maybe, as a kwarg on the non-interactive one...

**Comment by christopher-dG** [comment]
This has been implemented in #72, but there's some work that needs to happen before it can be merged and released (#61) which depends on me finding some time and motivation.

**Comment by arnavs** [comment]
Sounds good @christopher-dG. 

Let me know if there's anything someone on the outside (e.g. me) can help slog through.

**Comment by christopher-dG** [comment]
Gonna close this since other issues/PRs cover it. I'm making lots of progress on the prerequisite work.
