### ISSUE TITLE
Latest Travis CI changes : Windows + 32bit

### ISSUE THREAD

**Issue by aminya** [invenia/PkgTemplates.jl#87]
Travis CI has added support for Windows and also for 32bit builds. It is useful if we update the template to include the latest improvements.
https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187
https://discourse.julialang.org/t/32-bit-linux-julia-builds-are-now-available-on-travis-ci/27786

**Comment by christopher-dG** [comment]
This is covered in #61, which should hopefully be coming soon.
