### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by christopher-dG** [invenia/PkgTemplates.jl#9]
[PackageGenerator.jl](https://github.com/bramtayl/PackageGenerator.jl) does some nice stuff with various APIs that would be nice to have.

**Comment by bramtayl** [comment]
Hey is there anything I can do to help here?

**Comment by christopher-dG** [comment]
Probably! I'm not really sure though, I haven't looked into this at all yet.

**Comment by bramtayl** [comment]
I've put all the API stuff up as a separate standalone package at https://github.com/bramtayl/OnlinePackage.jl This should allow users to use both PkgTemplates and OnlinePackage

**Comment by christopher-dG** [comment]
Closing in favour of #46
