### ISSUE TITLE
Make licenses displayed in sensible order in interactive mode

### ISSUE THREAD

**Issue by oxinabox** [invenia/PkgTemplates.jl#90]
Right now they show up in an arbitary order as we keep them in a `Dict`

```
License:
^  ISC: Internet Systems Consortium License
   MPL: Mozilla Public License, Version 2.0
   GPL-2.0+: GNU Public License, Version 2.0+
   LGPL-3.0+: Lesser GNU Public License, Version 3.0+
   ASL: Apache License, Version 2.0
   EUPL-1.2+: European Union Public Licence, Version 1.2+
   GPL-3.0+: GNU Public License, Version 3.0+
   LGPL-2.1+: Lesser GNU Public License, Version 2.1+
 > MIT: MIT "Expat" License
   BSD: Simplified "2-clause" BSD License
```

I this is clearly not the right order.
There is some bikeshedding to be done on the correct order.
(Alphabetical, vs Most commonly used, vs Most/Least restrictive)
but clearly we do not want this order.

**Comment by christopher-dG** [comment]
I think alphabetical is the way to go. Ideally, the menu can start on MIT but that depends on https://github.com/JuliaLang/julia/pull/30043.

**Comment by oxinabox** [comment]
Could we have MIT twice? Once at the top, and once alphabtrically?
Like the thing where country lists often show the _USA_
both at the top, and under _U_

**Comment by DilumAluthge** [comment]
Definitely I think we should strongly encourage MIT as the license choice.

**Comment by christopher-dG** [comment]
#61 sorts licenses alphabetically and pre-selects MIT, so that should solve this.

**Comment by Nosferican** [comment]
I am hesitant on pushing for a particular license, but if we were, I think ISC would be a better candidate these days than MIT Expat. It would also be nice to have the licenses support a language option. For example, for EUPL-2 (https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12).

**Comment by DilumAluthge** [comment]
I think the MIT expat license is the best option because it is the license used by (most components of) the Julia language itself

**Comment by christopher-dG** [comment]
I do like the language option idea, that would be easy to implement but just tedious to go find licenses in various languages.

**Comment by Nosferican** [comment]
For the language formats, I think it might depends on the licenses, but would be cool for some communities that are not English-only (e.g., Europe, Asia, Latin America).

As for the MIT Expat/ISC... They are both MIT family so there is no difference at all in the terms. I don't see any reason as for why current most common text flavor would be an argument. The only difference is in the flavor of the text (e.g., using the OSI approved text, the Expat flavor, the Choosealicense flavor, or ISC text with now redundant text removed). For instance, Julia is MIT licensed, but doesn't use the MIT Expat flavor text which most of the community uses and the difference has zero consequence.
