### ISSUE TITLE
Add Drone CI for ARM

### ISSUE THREAD

**Issue by oxinabox** [invenia/PkgTemplates.jl#93]
See https://discourse.julialang.org/t/testing-on-arm-with-drone-ci/25871

**Comment by giordano** [comment]
Drone is quite nice and so far the only service I tried that allows testing on ARM.  It helped us spotting an issue with openlibm, see https://github.com/JuliaMath/FFTW.jl/issues/104.

As I wrote in the post on discourse, the only pain with configuring it is that the YAML file is quite annoying to write (I consistently did something wrong when I tried to write it myself, but PkgTemplate would help on this) and extend afterwards (you need to copy several lines).  The jsonnet file is way easier to maintain, but if you go by the jsonnet way you then need to keep both the jsonnet and the YAML files and update the latter from the former using Drone CLI.

If you're ok with all this mess, I might be able to try and add Drone CI to PkgTtemplate sometime in the future (unless someone else beats me at it).
