### ISSUE TITLE
github.user value misleading

### ISSUE THREAD

**Issue by AlexandreChern** [invenia/PkgTemplates.jl#97]
When I tried to use Template() function `Template()` without value for user key, I got this error message
`ERROR: ArgumentError: No GitHub username found, set one with user=username`
I trace it back to the template.jl file and find these code confusing. I didn't recall having key "github.user" when I set up git configurations. Why it isn't
 ` user = LibGit2.getconfig("user.name", "") `, 
this will return my git user name.
https://github.com/invenia/PkgTemplates.jl/blob/895f2be769970b5920aaab7bcc98de14a4de7580/src/template.jl#L64-L69

**Comment by christopher-dG** [comment]
`user.name` should not your GitHub username, it should be your real name. For me, it's "Chris de Graaf". But what we want is your GitHub (or other service) username ("christopher-dG" for me).

No, `github.user` is indeed not a "default" Git configuration like `user.name` and `user.email`, but it's somewhat common and easy enough to set once and forget. And if you don't want to do that, then you just have to do exactly what the error message tells you to do.

Doe that make things clearer?

**Comment by AlexandreChern** [comment]
> `user.name` should not your GitHub username, it should be your real name. For me, it's "Chris de Graaf". But what we want is your GitHub (or other service) username ("christopher-dG" for me).
> 
> No, `github.user` is indeed not a "default" Git configuration like `user.name` and `user.email`, but it's somewhat common and easy enough to set once and forget. And if you don't want to do that, then you just have to do exactly what the error message tells you to do.
> 
> Doe that make things clearer?

Thanks, I see.
